### ISSUE TITLE
Read Mode

### ISSUE THREAD

**Issue by rafaelpassarela** [rafaelpassarela/ng2-file-reader#2]
Allow different forms for reading the file content 
- Text
- <s>Binary</s>
- Url Data
- Array

**Comment by BatshevaAmor** [comment]
I'm trying to read an excel file, but the data returns as symbols:
W6°�/���zf���g���^T�'U�w�p�3��$�y����4[�W����=��b�ͫwd!�+q�̎.�'�Z9=*��y6���9j_R��i����ut�՝�@���&<��І .....
[It happens just with excel files and not with csv files]
What can I do?
